package me.aliahad.audioplayer.ui.theme

import androidx.compose.ui.graphics.Color

// Light mode palette
val LightBackground = Color(0xFFFFF8F0)
val LightOnBackground = Color(0xFF3E2723)
val LightSurface = Color(0xFFFFF8F0)
val LightOnSurface = Color(0xFF3E2723)
val LightSurfaceVariant = Color(0xFFF0E6D6)
val LightOnSurfaceVariant = Color(0xFF6D4C41)
val LightSurfaceContainerLow = Color(0xFFFFF3E8)
val LightSurfaceContainer = Color(0xFFFFEED9)
val LightSurfaceContainerHigh = Color(0xFFFFE8CC)
val LightPrimary = Color(0xFF5D4037)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD7CCC8)
val LightOnPrimaryContainer = Color(0xFF3E2723)
val LightSecondary = Color(0xFF795548)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFEFEBE9)
val LightOnSecondaryContainer = Color(0xFF4E342E)
val LightTertiary = Color(0xFF8D6E63)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightError = Color(0xFFB3261E)
val LightOnError = Color(0xFFFFFFFF)
val LightOutline = Color(0xFFA1887F)
val LightOutlineVariant = Color(0xFFD7CCC8)

// Night mode palette
val NightBackground = Color(0xFF2C1E17)
val NightOnBackground = Color(0xFFF5E6D3)
val NightSurface = Color(0xFF2C1E17)
val NightOnSurface = Color(0xFFF5E6D3)
val NightSurfaceVariant = Color(0xFF4E342E)
val NightOnSurfaceVariant = Color(0xFFD7CCC8)
val NightSurfaceContainerLow = Color(0xFF3A2A20)
val NightSurfaceContainer = Color(0xFF443025)
val NightSurfaceContainerHigh = Color(0xFF4E382C)
val NightPrimary = Color(0xFFEFCEAD)
val NightOnPrimary = Color(0xFF3E2723)
val NightPrimaryContainer = Color(0xFF5D4037)
val NightOnPrimaryContainer = Color(0xFFEFCEAD)
val NightSecondary = Color(0xFFD7CCC8)
val NightOnSecondary = Color(0xFF3E2723)
val NightSecondaryContainer = Color(0xFF5D4037)
val NightOnSecondaryContainer = Color(0xFFD7CCC8)
val NightTertiary = Color(0xFFFFAB91)
val NightOnTertiary = Color(0xFF3E2723)
val NightError = Color(0xFFF2B8B5)
val NightOnError = Color(0xFF601410)
val NightOutline = Color(0xFFA1887F)
val NightOutlineVariant = Color(0xFF4E342E)
